import random
import math
from typing import List, Set, Tuple

# Type aliases for clarity.
EdgeList = List[Tuple[int, int]]
VertexSets = List[Set[int]]


def sim_annealing_cover(graph: List[Set[int]]) -> Set[int]:
    """
    Simulated annealing algorithm for vertex cover.

    The algorithm uses a cost function that combines the size of the vertex cover
    and a penalty for each uncovered edge. Moves are generated by flipping the
    membership (in/out of the cover) of a randomly chosen vertex. Moves that
    reduce the cost are always accepted; moves that increase the cost may be accepted
    with a probability that decreases as the temperature cools.

    :param graph: The graph represented as an adjacency list.
                  graph[i] is a set of vertices adjacent to vertex i.
    :return: A set of vertices that form a vertex cover.
    """
    n = len(graph)
    # Start with a trivial cover that contains all vertices.
    current_cover: Set[int] = set(range(n))

    # Penalty weight is chosen high enough to strongly discourage uncovered edges.
    penalty_weight = n + 1

    def cost(cover: Set[int]) -> int:
        """Cost function: size of the cover plus penalty for each uncovered edge."""
        uncovered = 0
        # Iterate over each undirected edge once.
        for i in range(n):
            for j in graph[i]:
                if j > i:  # ensure each edge is considered only once.
                    if i not in cover and j not in cover:
                        uncovered += 1
        return len(cover) + penalty_weight * uncovered

    current_cost = cost(current_cover)
    best_cover = current_cover.copy()
    best_cost = current_cost

    # Simulated annealing parameters.
    T = 100.0  # initial temperature
    T_min = 1e-3  # minimum temperature threshold
    alpha = 0.995  # cooling rate
    iterations_per_temp = 100  # iterations at each temperature

    while T > T_min:
        for _ in range(iterations_per_temp):
            # Randomly choose a vertex to flip.
            v = random.randint(0, n - 1)
            new_cover = current_cover.copy()
            if v in new_cover:
                new_cover.remove(v)
            else:
                new_cover.add(v)

            new_cost = cost(new_cover)
            delta = new_cost - current_cost

            # Accept the move if it improves cost, or probabilistically if it worsens cost.
            if delta < 0 or random.random() < math.exp(-delta / T):
                current_cover = new_cover
                current_cost = new_cost
                # Update best found solution.
                if current_cost < best_cost:
                    best_cover = current_cover.copy()
                    best_cost = current_cost
        T *= alpha  # Cool down.

    return best_cover
